server:
  port: 8982

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    flyway:
      enabled: false

#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    baseline-description: "init"
#    baseline-version: 0
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}